---
- name: Replace secrets and env vars in acceptance and commands
  hosts: localhost
  vars:
    env_files_path: "./automation/support/env/"
    template_file: "{{ env_files_path }}{{ env | default('default_env') }}.env.yml"
  vars_files:
    - "./automation/support/secrets.yml"
    - "./automation/support/config.yml"
  
  tasks:
    - name: Check if specific environment template file exists
      stat:
        path: "{{ template_file }}"
      register: template_file_check

    - name: Set template file if exists
      include_vars: "{{ template_file }}"
      when: template_file_check.stat.exists
      ignore_errors: true
    
    - name: Find all acceptance and commands yml files
      find:
        paths:
          - ./automation/acceptance
          - ./automation/support/commands
        recurse: yes
        patterns: "*.yml"
      register: yml_files

    - name: Replace values secrets and env vars in acceptance and commands
      template:
        src: "{{ item.path }}"
        dest: "{{ item.path }}"
      loop: "{{ yml_files.files }}"
      when: item.path != "updated_test.yml" # Exclude the updated file itself

    - name: Loop over acceptance and commands yml files
      ansible.builtin.find:
        paths: "{{ item }}"
        patterns: "*.yml"
        recurse: yes
      register: yml_files
      loop:
        - ./automation/acceptance
        - ./automation/support/commands

    - name: Replace test variables on acceptance and command yml files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '\$var_(\w+)'
        replace: '${Cypress.env("\1")}'
      with_items: "{{ yml_files.results | map(attribute='files') | list }}"